### ISSUE TITLE
Installation not apparently working

### ISSUE THREAD

**Issue by samuell** [trustmaster/pyflyde#3]
Hi @trustmaster , excited to try out this library!

I had problems installing it though.

`pip install pyflyde` gives me:

```bash
(pyflyde) [shl pyflyde]$ pip install pyflyde
ERROR: Could not find a version that satisfies the requirement pyflyde (from versions: none)
ERROR: No matching distribution found for pyflyde
```

And if I try to install it with a local, editable installation:

```bash
$ pip install -e .
Obtaining file:///home/shl/proj/24/62-pyflyde/pyflyde
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///home/shl/proj/24/62-pyflyde/pyflyde has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

Versions:
```bash
$ python --version
Python 3.12.4

(pyflyde) [shl pyflyde]$ pip --version
pip 21.3.1 from /home/shl/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pip (python 3.6)
```

(I'm using [pixi](https://pixi.sh/) to set up a local environment).

**Comment by trustmaster** [comment]
Hey @samuell ! Thanks for checking it out!

What I find suspicious in the output provided, is that when you run PIP it seems to run in a venv with Python 3.6. That could be the reason.

As for editable mode, I'll add support for it, that should be relatively easy.

**Comment by trustmaster** [comment]
After googling a bit, e.g. [this](https://discuss.python.org/t/pip-complains-your-backend-does-not-support-editable-installs-with-latest-setuptools/26387/11) this seems to be an issue with outdated PIP (21.3.1 was released 3 years ago) that doesn't support recent setuptools and pyproject.toml versions.

**Comment by samuell** [comment]
> What I find suspicious in the output provided, is that when you run PIP it seems to run in a venv with Python 3.6. That could be the reason.

Ah, indeed, my bad there! I had missed that pixi doesn't install pip as part of the python installation. A simple `pixi add pip` solved it :relieved:
